// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPMRsFJUje1kSfOEj-MW-OnrOB1BLv1qU',
    appId: '1:663873174672:android:b6557823d5118590dd2c15',
    messagingSenderId: '663873174672',
    projectId: 'vodatracking',
    databaseURL: 'https://vodatracking-default-rtdb.firebaseio.com',
    storageBucket: 'vodatracking.firebasestorage.app',
  );

  // iOS: run `flutterfire configure --project=vodatracking --platforms=ios` to populate
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '663873174672',
    projectId: 'vodatracking',
    databaseURL: 'https://vodatracking-default-rtdb.firebaseio.com',
    storageBucket: 'vodatracking.firebasestorage.app',
    iosBundleId: 'com.vodafone.vodafoneCashTracker',
  );

  // Web: run `flutterfire configure --project=vodatracking --platforms=web` to populate
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2sxPnW7eTirrUH1p8bvBgM3QrAFCz7QU',
    appId: '1:663873174672:web:48c29d4cb9a2f3f5dd2c15',
    messagingSenderId: '663873174672',
    projectId: 'vodatracking',
    databaseURL: 'https://vodatracking-default-rtdb.firebaseio.com',
    storageBucket: 'vodatracking.firebasestorage.app',
    authDomain: 'vodatracking.firebaseapp.com',
    measurementId: 'G-FYLNJZGRV8',
  );
}